server:
  port: 7008
spring:
  application:
    name: cart-service
  redis:
    host: 172.16.145.141
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
leyou:
  jwt:
    pubKeyPath: /home/cloudlandboy/Project/leyou/rsa/rsa.pub # 公钥地址
    cookieName: LEYOU_TOKEN # cookie的名称